version: '3'

services:
    postgres:
        image: postgres:9.6
        container_name: {{cookiecutter.project_slug}}_postgres
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata # persist data on the local filesystem.
        volumes:
            - /var/lib/postgresql/data/pgdata

    webserver:
        build:
            args:
              - VENV={{cookiecutter.project_slug}}
            context: ..
            dockerfile: docker/Dockerfile
        container_name: {{cookiecutter.project_slug}}_app
        #image: your_registry/{{cookiecutter.project_slug}}_app
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=ih6k0MdoZCSWL_gqgqJnAw9LjLFRtbiFfZgtmajmOC8=
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    lab:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: {{cookiecutter.project_slug}}_lab
        restart: always
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        command: lab
        volumes:
            - ./notebooks:/app/notebooks
        ports:
            - "8888"


